// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ_nT2d0mbGGc8rTRSIX9aUtVXzR0cY0Y',
    appId: '1:749564370972:web:a30410a7959c7c0ca27fd9',
    messagingSenderId: '749564370972',
    projectId: 'fitpass-app-3f52e',
    authDomain: 'fitpass-app-3f52e.firebaseapp.com',
    storageBucket: 'fitpass-app-3f52e.firebasestorage.app',
    measurementId: 'G-VVF7S6VWK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBtG6wdYb9yxJ2TID5nDDSUO5UclTUkc4',
    appId: '1:749564370972:android:c2616479557970a5a27fd9',
    messagingSenderId: '749564370972',
    projectId: 'fitpass-app-3f52e',
    storageBucket: 'fitpass-app-3f52e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Hl8KW0UGpOBmoBa074noJbln3_g3LYo',
    appId: '1:749564370972:ios:2a9cdc19c0065f48a27fd9',
    messagingSenderId: '749564370972',
    projectId: 'fitpass-app-3f52e',
    storageBucket: 'fitpass-app-3f52e.firebasestorage.app',
    iosBundleId: 'com.example.fitpassWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Hl8KW0UGpOBmoBa074noJbln3_g3LYo',
    appId: '1:749564370972:ios:2a9cdc19c0065f48a27fd9',
    messagingSenderId: '749564370972',
    projectId: 'fitpass-app-3f52e',
    storageBucket: 'fitpass-app-3f52e.firebasestorage.app',
    iosBundleId: 'com.example.fitpassWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ_nT2d0mbGGc8rTRSIX9aUtVXzR0cY0Y',
    appId: '1:749564370972:web:18065930543849b0a27fd9',
    messagingSenderId: '749564370972',
    projectId: 'fitpass-app-3f52e',
    authDomain: 'fitpass-app-3f52e.firebaseapp.com',
    storageBucket: 'fitpass-app-3f52e.firebasestorage.app',
    measurementId: 'G-G7BHTMPPY7',
  );
}
